name: Build, Deploy to DockerHub

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker CLI
        uses: docker/setup-qemu-action@v2

      - name: Build Docker images
        run: |
          make docker-build-all

      - name: Push Docker images to DockerHub
        env:
          VERSION_TAG: ${{ github.sha }} 
        run: |
          # Tag and push for client-react-nginx image
          docker tag devs-today-test-app-react-client-nginx ${{ secrets.DOCKERHUB_USERNAME }}/devs-today-test-app-react-client-nginx:latest
          docker tag devs-today-test-app-react-client-nginx ${{ secrets.DOCKERHUB_USERNAME }}/devs-today-test-app-react-client-nginx:${{ env.VERSION_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devs-today-test-app-react-client-nginx:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devs-today-test-app-react-client-nginx:${{ env.VERSION_TAG }}

          # Tag and push for api-nest image
          docker tag devs-today-test-app-api-nest ${{ secrets.DOCKERHUB_USERNAME }}/devs-today-test-app-devs-today-test-app-api-nest:latest
          docker tag devs-today-test-app-api-nest ${{ secrets.DOCKERHUB_USERNAME }}/devs-today-test-app-apidevs-today-test-app-api-nest{ env.VERSION_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devs-today-test-app-api-nest:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devs-today-test-app-api-nest:${{ env.VERSION_TAG }}
